In [2]:
import numpy as np
import pandas as pd
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.pipeline import Pipeline, FeatureUnion
from sklearn.base import BaseEstimator, TransformerMixin
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, classification_report

In [3]:
import pandas as pd
import numpy as np
df = pd.read_csv("/home/ahmed/Desktop/Technocolabs_Internship/Week8(ML Pipline deployment)/new_preprocessed.csv")
df.sample(10)

category_code     status  founded_at  closed_at country_code  \
5416         finance  operating        2011       2021          CAN   
59204            web   acquired        2011          0          USA   
34022    games_video  operating        2012       2021          GBR   
5737             web  operating        2010       2021          USA   
12911  manufacturing  operating        2012       2021          USA   
25597         health  operating        2011       2021          USA   
52564            web  operating        2007       2021          BGR   
46975       hardware  operating        2004       2021          CAN   
50374       software  operating        2004       2021          ISR   
19020       software  operating        2000       2021          USA   

       first_funding_at  last_funding_at  funding_rounds  funding_total_usd  \
5416             2010.0           2010.0             1.0       4.325189e+06   
59204            2011.0           2013.0             1.0       4.325189e+06   
34022            2011.0           2013.0             1.0       4.325189e+06   
5737             2011.0           2011.0             1.0       5.000000e+05   
12911            2012.0           2012.0             1.0       1.000000e+06   
25597            2012.0           2012.0             1.0       1.400000e+05   
52564            2011.0           2013.0             1.0       4.325189e+06   
46975            2009.0           2010.0             2.0       7.200000e+06   
50374            2005.0           2005.0             1.0       5.000000e+05   
19020            2011.0           2013.0             1.0       4.325189e+06   

       first_milestone_at  last_milestone_at  milestones  relationships  \
5416               2013.0             2013.0         1.0            3.0   
59204              2011.0             2011.0         1.0            6.0   
34022              2013.0             2013.0         1.0            1.0   
5737               2012.0             2012.0         1.0            1.0   
12911              2009.0             2010.0         1.0            1.0   
25597              2009.0             2010.0         1.0            3.0   
52564              2009.0             2010.0         1.0            2.0   
46975              2009.0             2010.0         1.0            1.0   
50374              2009.0             2010.0         1.0            1.0   
19020              2009.0             2010.0         1.0            2.0   

       isClosed  
5416          1  
59204         0  
34022         1  
5737          1  
12911         1  
25597         1  
52564         1  
46975         1  
50374         1  
19020         1

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 60275 entries, 0 to 60274
Data columns (total 14 columns):
 #   Column              Non-Null Count  Dtype  
---  ------              --------------  -----  
 0   category_code       60275 non-null  object 
 1   status              60275 non-null  object 
 2   founded_at          60275 non-null  int64  
 3   closed_at           60275 non-null  int64  
 4   country_code        60275 non-null  object 
 5   first_funding_at    60275 non-null  float64
 6   last_funding_at     60275 non-null  float64
 7   funding_rounds      60275 non-null  float64
 8   funding_total_usd   60275 non-null  float64
 9   first_milestone_at  60275 non-null  float64
 10  last_milestone_at   60275 non-null  float64
 11  milestones          60275 non-null  float64
 12  relationships       60275 non-null  float64
 13  isClosed            60275 non-null  int64  
dtypes: float64(8), int64(3), object(3)
memory usage: 6.4+ MB


In [5]:
df['funding_rounds'].unique()

array([1., 3., 2.])

In [34]:
df['funding_total_usd'].unique().max()

26728460.0

In [6]:
df['milestones'].unique()

array([1., 3., 4., 2., 5., 6., 7.])

In [7]:
df['relationships'].unique()

array([2.000e+00, 1.000e+00, 1.400e+01, 3.000e+00, 9.000e+00, 6.000e+00,
       5.000e+00, 4.000e+00, 1.200e+01, 8.000e+00, 7.000e+00, 1.900e+01,
       1.000e+01, 1.000e+02, 2.300e+01, 1.300e+01, 2.700e+01, 1.100e+01,
       5.900e+01, 1.600e+01, 2.100e+01, 1.700e+01, 2.000e+01, 6.600e+01,
       1.800e+01, 1.500e+01, 2.200e+01, 3.700e+01, 1.030e+02, 2.400e+01,
       9.500e+01, 3.000e+01, 1.010e+02, 4.300e+01, 2.600e+01, 2.500e+01,
       2.800e+01, 3.600e+01, 5.100e+01, 3.400e+01, 3.100e+01, 6.000e+01,
       2.900e+01, 3.200e+01, 3.300e+01, 7.000e+01, 6.300e+01, 9.200e+01,
       4.000e+01, 7.300e+01, 5.700e+01, 4.700e+01, 7.500e+01, 4.100e+01,
       4.800e+01, 5.800e+01, 7.200e+01, 9.600e+01, 4.500e+01, 8.000e+01,
       7.800e+01, 3.500e+01, 4.690e+02, 1.810e+02, 1.630e+02, 3.800e+01,
       5.600e+01, 4.600e+01, 7.100e+01, 3.900e+01, 4.400e+01, 5.500e+01,
       6.400e+01, 6.140e+02, 1.020e+02, 3.240e+02, 2.960e+02, 2.540e+02,
       9.400e+01, 8.400e+01, 6.800e+01, 1.050e+02, 

In [8]:
df['category_code'].unique()

array(['advertising', 'cleantech', 'web', 'games_video', 'mobile',
       'software', 'network_hosting', 'consulting', 'finance',
       'education', 'medical', 'manufacturing', 'enterprise', 'other',
       'ecommerce', 'public_relations', 'hardware', 'search', 'analytics',
       'news', 'government', 'security', 'biotech', 'photo_video',
       'travel', 'health', 'semiconductor', 'social', 'legal',
       'transportation', 'hospitality', 'sports', 'nonprofit', 'fashion',
       'messaging', 'music', 'automotive', 'design', 'real_estate',
       'local', 'pets', 'nanotech'], dtype=object)

In [9]:
df['status'].unique()

array(['operating', 'acquired', 'closed', 'ipo'], dtype=object)

In [10]:
df['country_code'].unique()

array(['MAR', 'IND', 'USA', 'AUS', 'FRA', 'JPN', 'NLD', 'EGY', 'ISR',
       'GBR', 'THA', 'AUT', 'IRL', 'SWE', 'DEU', 'BRA', 'FIN', 'RUS',
       'SGP', 'MEX', 'CHN', 'ESP', 'ISL', 'KOR', 'TUR', 'DNK', 'PAK',
       'HUN', 'CAN', 'POL', 'GRC', 'PRT', 'BLR', 'CSS', 'MKD', 'ARG',
       'CHE', 'UKR', 'ITA', 'NZL', 'CZE', 'VNM', 'NOR', 'HRV', 'BEN',
       'CHL', 'GHA', 'ZAF', 'MYS', 'EST', 'BEL', 'SVK', 'TWN', 'CRI',
       'HKG', 'BGD', 'BOL', 'LBN', 'LUX', 'COL', 'PHL', 'ARE', 'IDN',
       'ROM', 'ANT', 'NGA', 'LKA', 'SWZ', 'VGB', 'MLT', 'SAU', 'KEN',
       'BGR', 'PER', 'LVA', 'CYP', 'LAO', 'NPL', 'MDA', 'CMR', 'UGA',
       'TUN', 'URY', 'MUS', 'VEN', 'OMN', 'ECU', 'KWT', 'JOR', 'LTU',
       'ALB', 'SVN', 'QAT', 'PST', 'REU', 'GTM', 'PCN', 'BHS', 'GEO',
       'BWA', 'DZA', 'GRD', 'GIB', 'PAN', 'MTQ', 'PRI', 'BIH', 'DMA',
       'BHR', 'SYC', 'SLE', 'TTO', 'VCT', 'ARA', 'BRB', 'NAM', 'SLV',
       'AFG', 'BLZ', 'UZB', 'LIE', 'IRN', 'ARM', 'ATG', 'UMI', 'DOM',
       'MDV', 'MMR',

In [11]:
from sklearn.preprocessing import LabelEncoder
encoded_labels = LabelEncoder()
encoded_labels

LabelEncoder()

In [12]:
df['status'] = encoded_labels.fit_transform(df['status'])
df['country_code'] = encoded_labels.fit_transform(df['country_code'])
df['category_code'] = encoded_labels.fit_transform(df['category_code'])


In [13]:
X = df.drop(['status'], axis=1)
y_binary = df['isClosed']
y_multiclass = df[['status']]

In [14]:
X_train, X_test, y_binary_train, y_binary_test, y_multiclass_train, y_multiclass_test = train_test_split(
    X, y_binary, y_multiclass, test_size=0.2, random_state=42
)

In [15]:
# Custom transformer to add binary classifier output as a feature
class AddBinaryClassifierOutput(BaseEstimator, TransformerMixin):
    def __init__(self, binary_model):
        self.binary_model = binary_model

    def fit(self, X, y=None):
        self.binary_model.fit(X, y)
        return self

    def transform(self, X):
        binary_predictions = self.binary_model.predict(X)
        binary_predictions = binary_predictions.reshape(-1, 1)
        return np.hstack((X, binary_predictions))


In [16]:
# Define the binary and multiclass models
binary_model = LogisticRegression()
multiclass_model1 = RandomForestClassifier()
multiclass_model2 = KNeighborsClassifier()

In [17]:
# Create the pipeline
pipeline = Pipeline([
    ('add_binary_output', AddBinaryClassifierOutput(binary_model)),
    ('multiclass_classifier', multiclass_model1)
])

In [18]:
# Create the pipeline
pipeline2 = Pipeline([
    ('add_binary_output', AddBinaryClassifierOutput(binary_model)),
    ('multiclass_classifier', multiclass_model2)
])

In [19]:
# Train the combined pipeline
pipeline.fit(X_train, y_multiclass_train)

/home/ahmed/.local/lib/python3.10/site-packages/sklearn/utils/validation.py:1310: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/home/ahmed/.local/lib/python3.10/site-packages/sklearn/linear_model/_logistic.py:469: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
/home/ahmed/.local/lib/python3.10/site-packages/sklearn/base.py:1473: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example 

Pipeline(steps=[('add_binary_output',
                 AddBinaryClassifierOutput(binary_model=LogisticRegression())),
                ('multiclass_classifier', RandomForestClassifier())])

In [20]:
# Predict on the test set
y_pred = pipeline.predict(X_test)

In [21]:
# Evaluate the pipeline
accuracy = accuracy_score(y_multiclass_test, y_pred)
report = classification_report(y_multiclass_test, y_pred)

In [22]:
print(f'Accuracy: {accuracy:.3f}')
print('Classification Report:')
print(report)

Accuracy: 0.991
Classification Report:
              precision    recall  f1-score   support

           0       1.00      0.99      0.99       713
           1       0.97      1.00      0.99       289
           2       0.56      0.10      0.17       103
           3       0.99      1.00      1.00     10950

    accuracy                           0.99     12055
   macro avg       0.88      0.77      0.79     12055
weighted avg       0.99      0.99      0.99     12055



# KNN

In [23]:
# Train the combined pipeline
pipeline2.fit(X_train, y_multiclass_train)

/home/ahmed/.local/lib/python3.10/site-packages/sklearn/utils/validation.py:1310: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/home/ahmed/.local/lib/python3.10/site-packages/sklearn/linear_model/_logistic.py:469: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
/home/ahmed/.local/lib/python3.10/site-packages/sklearn/neighbors/_classification.py:238: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_sam

Pipeline(steps=[('add_binary_output',
                 AddBinaryClassifierOutput(binary_model=LogisticRegression())),
                ('multiclass_classifier', KNeighborsClassifier())])

In [24]:
# Predict on the test set
y_pred = pipeline2.predict(X_test)

In [25]:
# Evaluate the pipeline
accuracy = accuracy_score(y_multiclass_test, y_pred)
report = classification_report(y_multiclass_test, y_pred)

In [26]:
print(f'Accuracy: {accuracy:.3f}')
print('Classification Report:')
print(report)

Accuracy: 0.964
Classification Report:
              precision    recall  f1-score   support

           0       0.98      0.80      0.88       713
           1       0.84      0.39      0.54       289
           2       0.21      0.03      0.05       103
           3       0.96      1.00      0.98     10950

    accuracy                           0.96     12055
   macro avg       0.75      0.56      0.61     12055
weighted avg       0.96      0.96      0.96     12055



# Save Pipeline

In [27]:
import pickle 
with open('Building_Machine_Learning_Pipeline_on_Startup_Acquisition_Status.pickle','wb')as f :
    pickle.dump(pipeline,f)

In [28]:
import json 
columns ={
    'data_columns':[col.lower() for col in X.columns]
}
with open('Building_Machine_Learning_Pipeline_on_Startup_Acquisition_Status_Columns.json','w') as f:
    f.write(json.dumps(columns))

In [36]:
import pandas
import numpy
import sklearn
import streamlit

print("pandas version:", pandas.__version__)
print("numpy version:", numpy.__version__)
print("scikit-learn version:", sklearn.__version__)
print("streamlit version:", streamlit.__version__)


pandas version: 1.5.3
numpy version: 1.26.4
scikit-learn version: 1.5.0
streamlit version: 1.32.2
